#!/bin/sh
set -eu

cd $HOME/dotfiles
git submodule update --init

for target in $HOME/dotfiles/bin/*; do
	chmod +x $target
done

for target in $HOME/dotfiles/install/*.sh; do
	. $target
done

install_buildessential
install_curl
install_git && initialize_git
install_vim && initialize_vim
install_vscode
install_powershell && initialize_powershell

initialize_bash
